# An environment to develop, build, test, and document WBMsed.
name: wbmsed
channels:
  - conda-forge
dependencies:
  - c-compiler
  - cxx-compiler
  - make
  - cmake
  - shapelib
  - netcdf4
  - udunits2
  - gdal
